.TH "MultiplePipes" 3 "Mon Apr 5 2021" "AUSH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultiplePipes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBisPipe\fP"
.br
.ti -1c
.RI "char * \fBlefthandPipe\fP"
.br
.ti -1c
.RI "char * \fBrighthandPipe\fP"
.br
.ti -1c
.RI "char ** \fBlefthandPipeParsed\fP"
.br
.ti -1c
.RI "char ** \fBrighthandPipeParsed\fP"
.br
.ti -1c
.RI "\fBAUSH_CMD_FLAG\fP \fBlefthandFlag\fP"
.br
.ti -1c
.RI "\fBAUSH_CMD_FLAG\fP \fBrighthandFlag\fP"
.br
.ti -1c
.RI "int \fBleftArgc\fP"
.br
.ti -1c
.RI "int \fBrightArgc\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int isPipe"

.SS "int leftArgc"

.SS "\fBAUSH_CMD_FLAG\fP lefthandFlag"

.SS "char* lefthandPipe"

.SS "char** lefthandPipeParsed"

.SS "int rightArgc"

.SS "\fBAUSH_CMD_FLAG\fP righthandFlag"

.SS "char* righthandPipe"

.SS "char** righthandPipeParsed"


.SH "Author"
.PP 
Generated automatically by Doxygen for AUSH from the source code\&.
